// Generated by tauri-specta from src-tauri. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Opens the repository containing `path` in a new session that emits `repoChanged` events, or
	 *  returns the session that already has that repository open.
	 */
	openRepo: (path: string) => __TAURI_INVOKE<OpenedRepo>("open_repo", { path }),
	/**  Closes a session and stops watching its repository. Closing a closed session does nothing. */
	closeRepo: (session: SessionId) => __TAURI_INVOKE<null>("close_repo", { session }),
	/**  Re-reads a session's repository. The generation changes only if something visible changed. */
	refresh: (session: SessionId) => __TAURI_INVOKE<RepoInfo>("refresh", { session }),
	/**  Rows `start..start + len` of the current snapshot, clamped to the rows that exist. */
	rows: (session: SessionId, start: number, len: number) => __TAURI_INVOKE<RowsPage>("rows", { session, start, len }),
	/**
	 *  Where the row showing `id` (a commit, a stash, or the all-zero id for uncommitted changes) is
	 *  in the current snapshot; `row` is `null` if no row shows it.
	 */
	locate: (session: SessionId, id: Oid) => __TAURI_INVOKE<RowLocation>("locate", { session, id }),
	/**  Full details of one commit; `null` if `id` isn't a commit. */
	commitDetails: (session: SessionId, id: Oid) => __TAURI_INVOKE<{
	id: Oid,
	parents: Oid[],
	author: Signature,
	committer: Signature,
	/**  Full commit message. */
	message: string,
	/**  Files changed relative to the first parent (or the empty tree for a root commit). */
	files: FileChange[],
} | null>("commit_details", { session, id }),
	/**
	 *  Files that differ between `from` and `to`, sorted by path; a `from` of `null` compares against
	 *  nothing. Reads the index and worktree as they are now.
	 */
	changes: (session: SessionId, from: 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" } | null, to: DiffSide) => __TAURI_INVOKE<FileChange[]>("changes", { session, from, to }),
	/**
	 *  How one file differs between `from` (`null`: nothing) and `to`. `path` names the file on the
	 *  `to` side; pass `oldPath` when it was renamed or copied from another path.
	 */
	fileDiff: (session: SessionId, from: 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" } | null, to: DiffSide, path: string, oldPath: string | null) => __TAURI_INVOKE<FileDiff>("file_diff", { session, from, to, path, oldPath }),
	/**
	 *  Runs `operation` on the repository of `session`. `id` identifies this request: running an id
	 *  that already ran on that session returns that run's outcome instead of running again. Failures
	 *  of the operation itself are an outcome, not a rejection; the call rejects only if the session
	 *  isn't open.
	 */
	runOperation: (session: SessionId, id: OpId, operation: Operation) => __TAURI_INVOKE<OpOutcome>("run_operation", { session, id, operation }),
	/**
	 *  Answers the credential prompt `id`; `null` cancels it, failing the operation that asked.
	 *  Answering a prompt that timed out or was already answered does nothing.
	 */
	answerPrompt: (id: number, answer: string | null) => __TAURI_INVOKE<void>("answer_prompt", { id, answer }),
	/**
	 *  What undo would restore now on the repository of `session`: the most recent operation on it
	 *  that can be undone, why it can't, or that there is nothing to undo. Run it with the `undo`
	 *  operation, naming the entry this returned.
	 */
	undoable: (session: SessionId) => __TAURI_INVOKE<Undoable>("undoable", { session }),
};

/** Events */
export const events = {
	credentialPrompt: makeEvent<CredentialPrompt>("credential-prompt"),
	opProgress: makeEvent<OpProgress>("op-progress"),
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
};

/* Types */
/**  The error every command rejects with. The UI shows `message`; `kind` only picks wording. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type ChangeStatus = "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChanged";

export type CheckoutTarget = 
/**  A local branch, by short name. */
{ kind: "branch"; name: string } | 
/**  A commit, detaching HEAD. */
{ kind: "commit"; id: Oid };

export type CommitDetails = {
	id: Oid,
	parents: Oid[],
	author: Signature,
	committer: Signature,
	/**  Full commit message. */
	message: string,
	/**  Files changed relative to the first parent (or the empty tree for a root commit). */
	files: FileChange[],
};

/**  A file git couldn't merge. */
export type ConflictFile = {
	/**  `/`-separated, relative to the worktree root. */
	path: string,
	/**
	 *  The file on disk no longer has conflict markers (or was deleted): continuing will take it
	 *  as it is.
	 */
	resolved: boolean,
};

/**  Git needs the user to type something. Answer with `answer_prompt(id, …)`. */
export type CredentialPrompt = {
	id: number,
	/**  Git's prompt, e.g. `Password for 'https://me@github.com': `. */
	text: string,
	/**  Mask the input: the answer is a password, token or passphrase. */
	secret: boolean,
};

export type DiffLine = {
	kind: LineKind,
	/**  The line without its terminator. */
	text: string,
	/**
	 *  True if this is the last line of its version and that version doesn't end with a newline
	 *  (git's `\ No newline at end of file`).
	 */
	noFinalNewline: boolean,
};

/**  One side of a comparison between two versions of the repository's files. */
export type DiffSide = 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" };

/**
 *  A line segment inside one row.
 * 
 *  A row is split at its node's vertical center. An [`Half::Upper`] segment runs from the row's
 *  top edge at lane `from` to the center at lane `to`; a [`Half::Lower`] segment runs from the
 *  center at lane `from` to the row's bottom edge at lane `to`. A lane passing straight through a
 *  row is one upper and one lower segment with `from == to`. Segments with `from == to ==
 *  GraphRow::column` are the node's own lane arriving or leaving, not a pass-through.
 */
export type Edge = {
	half: Half,
	from: number,
	to: number,
	color: number,
};

export type ErrorKind = 
/**  A command named a session that isn't open (any more). */
"noRepository" | "notARepository" | "git" | 
/**  A bug in FerGit. */
"internal";

export type FileChange = {
	/**  Path after the change, `/`-separated. */
	path: string,
	/**  Path before the change, for renames and copies. */
	oldPath: string | null,
	status: ChangeStatus,
	/**
	 *  Added lines; `None` for binary files (a NUL byte in the first 8000 bytes), submodules, and
	 *  files over 8 MiB on either side.
	 */
	additions: number | null,
	/**  Deleted lines; `None` in the same cases as `additions`. */
	deletions: number | null,
};

/**  How one file differs between two sides. */
export type FileDiff = 
/**
 *  Changed lines in hunks with three lines of context, as `git diff` shows them. No hunks means
 *  the contents are identical (a mode-only change, for example).
 */
{ kind: "text"; hunks: Hunk[] } | 
/**  A side is binary: a NUL byte within its first 8000 bytes. */
{ kind: "binary" } | 
/**  A side is larger than 8 MiB. */
{ kind: "tooLarge" } | 
/**
 *  The path is a submodule on at least one side; `old` and `new` are the commits it points to,
 *  `None` where that side has no submodule at the path.
 */
{ kind: "submodule"; old: Oid | null; new: Oid | null };

/**  Whether a push may replace commits on the remote. There is deliberately no unconditional force. */
export type ForceMode = 
/**  Only fast-forward the remote branch. */
{ kind: "none" } | 
/**
 *  Replace the remote branch, but only if it is still at `expected` (`None`: only if it doesn't
 *  exist), the tip the user was looking at. A remote branch that moved since, because someone
 *  else pushed, fails the push as [`OpErrorKind::StaleLease`] instead of losing their work.
 */
{ kind: "withLease"; expected: Oid | null };

/**
 *  Identifies one snapshot of a repository. Increases every time the visible state changes, and
 *  keeps increasing across repositories opened in the same process, so the UI can discard any
 *  response or event from an older snapshot, including one of a repository it opened before.
 */
export type Generation = number;

/**  Drawable geometry for one row of the graph. */
export type GraphRow = {
	/**  Lane holding this row's node; lane 0 is leftmost. */
	column: number,
	/**  Color index of the node. Unbounded; the UI maps it onto its palette (e.g. modulo its size). */
	color: number,
	/**  Line segments drawn within this row. */
	edges: Edge[],
};

export type Half = "upper" | "lower";

export type Hunk = {
	/**
	 *  First line of the hunk in the old version, 1-based; 0 when the hunk has no old lines (git's
	 *  `@@ -0,0 +1,3 @@`).
	 */
	oldStart: number,
	oldLines: number,
	/**  First line of the hunk in the new version, 1-based; 0 when the hunk has no new lines. */
	newStart: number,
	newLines: number,
	lines: DiffLine[],
};

export type LineKind = "context" | "added" | "removed";

export type MergeMode = 
/**  Fast-forward when the branch has no commits of its own, else create a merge commit. */
"ff" | 
/**  Always create a merge commit. */
"noFf" | 
/**  Commit the combined changes as one ordinary commit, recording no merge. */
"squash";

/**  A git object id (SHA-1). Crosses IPC as a 40-character lowercase hex string. */
export type Oid = string;

/**  Why an operation failed. */
export type OpError = {
	kind: OpErrorKind,
	/**  What went wrong and what to do about it, written for the user. */
	message: string,
	/**
	 *  Git's output (errors first, then anything it printed to stdout), with credentials removed.
	 *  Empty if git never ran.
	 */
	output: string,
};

export type OpErrorKind = 
/**
 *  A name isn't a valid ref name, a remote doesn't exist, or the repository isn't in a state
 *  the operation applies to (no current branch to pull, say). Git didn't run.
 */
"invalidInput" | 
/**  The branch or tag to create already exists. */
"alreadyExists" | 
/**  The branch to delete has commits that would become unreachable; deleting it needs `force`. */
"notFullyMerged" | 
/**  Uncommitted changes would be overwritten. */
"localChanges" | 
/**
 *  The remote has commits the local branch lacks (push), or the two diverged (pull), or a hook
 *  on the remote declined the push.
 */
"rejected" | 
/**  A lease-protected push found the remote branch somewhere other than expected. */
"staleLease" | 
/**
 *  A branch, HEAD or stash wasn't where the operation expected it (a reset's `expected` tip,
 *  what an undo would restore from), so nothing was changed.
 */
"moved" | 
/**  The remote wanted credentials that were missing, cancelled or wrong. */
"authFailed" | 
/**  Git couldn't be started. */
"gitNotFound" | 
/**  Any other failure; `message` has git's own words. */
"git";

/**
 *  Identifies one request to run an operation. The UI generates it; running the same id twice runs
 *  the operation once, so a double click or a retried request can't push twice.
 */
export type OpId = string;

/**
 *  How an operation ended. The repository is re-read either way (a failed fetch may still have
 *  updated some refs), and `info` describes the snapshot current afterwards.
 */
export type OpOutcome = { kind: "done"; info: RepoInfo } | { kind: "failed"; info: RepoInfo; error: OpError };

/**
 *  A line of git's progress for the operation `id` running on `session`, e.g.
 *  `Receiving objects: 45% (9/20)`.
 */
export type OpProgress = {
	session: SessionId,
	id: OpId,
	text: string,
};

/**  A repository `open_repo` opened, or found already open. */
export type OpenedRepo = {
	session: SessionId,
	info: RepoInfo,
};

/**
 *  Something the user asked to do to the repository, described by intent rather than as a git
 *  command line. Names are short ref names as shown on labels (`main`, `v1.0`); they are validated
 *  before git sees them, and never parsed as options.
 * 
 *  Serialized into the operation journal, which outlives the binary: variants and fields may be
 *  added, but never renamed or removed.
 */
export type Operation = 
/**
 *  Switch the worktree to a branch, or detach HEAD at a commit. Fails, changing nothing, if
 *  uncommitted changes would be overwritten.
 */
{ kind: "checkout"; target: CheckoutTarget } | 
/**
 *  Create a local branch at `at`, optionally switching to it and making it follow `upstream`
 *  (a full remote-tracking ref name such as `refs/remotes/origin/main`).
 */
{ kind: "createBranch"; name: string; at: Oid; checkout: boolean; upstream: string | null } | 
/**
 *  Ensure the local branch `name` doesn't exist: deleting one that is already gone succeeds.
 *  Without `force`, a branch with commits not merged into its upstream (or HEAD) is kept.
 */
{ kind: "deleteBranch"; name: string; force: boolean } | 
/**  Create a tag at `at`: annotated with `message` if there is one, lightweight otherwise. */
{ kind: "createTag"; name: string; at: Oid; message: string | null } | 
/**  Ensure the tag `name` doesn't exist: deleting one that is already gone succeeds. */
{ kind: "deleteTag"; name: string } | 
/**
 *  Download from `remote`, or from every remote when `None`, removing remote-tracking branches
 *  whose remote branch is gone if `prune` is set.
 */
{ kind: "fetch"; remote: string | null; prune: boolean } | 
/**
 *  Fetch the current branch's upstream and fast-forward the branch to it. Fails, changing no
 *  branch, if the two have diverged; merging and rebasing are separate operations.
 */
{ kind: "pull" } | 
/**
 *  Push the local branch `branch` to the branch of the same name on `remote` (the branch's push
 *  remote when `None`), making it the branch's upstream if `set_upstream`.
 */
{ kind: "push"; branch: string; remote: string | null; force: ForceMode; setUpstream: boolean } | 
/**
 *  Merge `from` into the current branch. Stopping with conflicts succeeds, leaving
 *  [`RepoState::Merging`].
 */
{ kind: "merge"; from: Rev; mode: MergeMode } | 
/**
 *  Replay the current branch's commits onto `onto`, without an editor. Stopping with conflicts
 *  succeeds, leaving [`RepoState::Rebasing`].
 */
{ kind: "rebase"; onto: Rev } | 
/**
 *  Apply the changes of `commits`, in this order, as new commits on the current branch.
 *  Stopping with conflicts succeeds, leaving [`RepoState::CherryPicking`].
 */
{ kind: "cherryPick"; commits: Oid[] } | 
/**
 *  Add a commit undoing the changes of `commit`. Stopping with conflicts succeeds, leaving
 *  [`RepoState::Reverting`].
 */
{ kind: "revert"; commit: Oid } | 
/**
 *  Move the local branch `branch` to `to`, but only if it is still at `expected`, the tip the
 *  user was looking at; otherwise it fails as [`OpErrorKind::Moved`], changing nothing. For the
 *  current branch, `mode` says what happens to the index and worktree.
 */
{ kind: "reset"; branch: string; to: Oid; mode: ResetMode; expected: Oid } | 
/**
 *  Finish what is in progress: stage the conflicted files (refused while any still has conflict
 *  markers), then commit and carry on with the rest of a rebase, cherry-pick or revert.
 */
{ kind: "continue" } | 
/**  Give up what is in progress, putting the branch and files back as they were before it. */
{ kind: "abort" } | 
/**  Leave out the commit a rebase, cherry-pick or revert stopped at, and carry on. */
{ kind: "skip" } | 
/**
 *  Save uncommitted changes (and untracked files, if `untracked`) as a new stash, leaving the
 *  worktree clean.
 */
{ kind: "stashPush"; message: string | null; untracked: boolean } | 
/**  Apply the changes of stash `stash@{index}`, which must still be the stash `id`, keeping it. */
{ kind: "stashApply"; index: number; id: Oid } | 
/**  Apply stash `stash@{index}` (still `id`) and remove it; a stash that conflicts is kept. */
{ kind: "stashPop"; index: number; id: Oid } | 
/**  Remove stash `stash@{index}`, which must still be the stash `id`. */
{ kind: "stashDrop"; index: number; id: Oid } | 
/**
 *  Put back what the journal entry `entry` recorded before it ran: the refs it moved (not
 *  remote-tracking ones), HEAD if it switched branches, a stash it dropped or pushed. Refused,
 *  changing nothing, if any of those has moved since.
 */
{ kind: "undo"; entry: OpId };

/**  A ref that differed between before and after an operation. `None` means the ref didn't exist. */
export type RefChange = {
	name: string,
	before: Oid | null,
	after: Oid | null,
};

/**  Declaration order is display order. */
export type RefKind = 
/**  Detached HEAD. */
"head" | "localBranch" | "remoteBranch" | "tag" | "stash";

export type RefLabel = {
	kind: RefKind,
	/**  Short name as the user reads it: `main`, `origin/main`, `v1.0`, `HEAD`, `stash@{0}`. */
	name: string,
	/**  Full ref name: `refs/heads/main`, `refs/remotes/origin/main`, `refs/tags/v1.0`, `HEAD`, `refs/stash`. */
	fullName: string,
	/**  True for the branch HEAD points to, and for the `HEAD` label of a detached HEAD. */
	isHead: boolean,
	/**
	 *  For a local branch with an upstream configured (`branch.<name>.merge`), that upstream and
	 *  how far the branch has diverged from it. `None` for every other ref.
	 */
	upstream: Upstream | null,
};

/**
 *  A branch splitting off or joining another, drawn where its line meets this row's commit.
 * 
 *  Git doesn't record which branch a commit was made on, so branch names are inferred: from the
 *  refs at a branch's tip and from merge commit messages (`Merge branch 'feature/x'`), carried down
 *  the branch's line. A name is `None` when nothing names the branch.
 */
export type Relation = 
/**
 *  The branch whose line comes down lane `lane` starts at this row's commit: this row's upper
 *  segment from lane `lane` into the node. `from` names the branch the commit is on.
 */
{ kind: "branchedFrom"; lane: number; branch: string | null; from: string | null } | 
/**
 *  This merge commit brings in the branch continuing in lane `lane`: this row's lower segment
 *  from the node to lane `lane`, one per non-first parent. `into` names the branch receiving
 *  the merge.
 */
{ kind: "merges"; lane: number; branch: string | null; into: string | null };

/**
 *  Sent when an open repository changed on disk and a newer snapshot is current. `info` is what
 *  `refresh` would return for `session`, so the UI handles both the same way.
 */
export type RepoChanged = {
	session: SessionId,
	info: RepoInfo,
};

export type RepoInfo = {
	/**  Worktree root, or the git directory for a bare repository. */
	root: string,
	/**  Display name: the last component of `root`. */
	name: string,
	generation: Generation,
	rowCount: number,
	/**  The commit HEAD points to; `None` in a repository without commits. */
	head: Oid | null,
	/**  Short name of the branch HEAD names (even one without commits yet); `None` when detached. */
	branch: string | null,
	/**  Whether a merge, rebase, cherry-pick or revert is in progress, and which files conflict. */
	state: RepoState,
};

/**
 *  What git is in the middle of. Stopping with conflicts is a normal state, not an error: the user
 *  resolves the files in their editor, then continues or aborts (see [`Operation::Continue`]).
 */
export type RepoState = 
/**  Nothing in progress, and no file has conflicts. */
{ kind: "clean" } | 
/**
 *  A merge stopped before committing. `heads` are the commits being merged in (none for a
 *  squash merge, which records no merge); `message` is the first line of the prepared message.
 */
{ kind: "merging"; heads: Oid[]; squash: boolean; message: string; conflicts: ConflictFile[] } | 
/**
 *  A rebase of `branch` (`None`: of a detached HEAD) onto `onto` stopped at commit `at`, which
 *  is step `step` of `total`.
 */
{ kind: "rebasing"; branch: string | null; onto: Oid | null; at: Oid | null; step: number; total: number; conflicts: ConflictFile[] } | 
/**  A cherry-pick stopped at `commit` (`None` if git no longer records which). */
{ kind: "cherryPicking"; commit: Oid | null; conflicts: ConflictFile[] } | 
/**  A revert stopped at `commit` (`None` if git no longer records which). */
{ kind: "reverting"; commit: Oid | null; conflicts: ConflictFile[] } | 
/**
 *  Files have conflicts but nothing is in progress: a stash that didn't apply cleanly. The
 *  stash is kept.
 */
{ kind: "unmerged"; conflicts: ConflictFile[] };

export type ResetMode = 
/**  Move the branch only; the undone commits' changes stay staged. */
"soft" | 
/**  Move the branch and reset the index; the changes stay in the files, unstaged. */
"mixed" | 
/**
 *  Move the branch and make the index and files match it, discarding uncommitted changes to
 *  tracked files. Discarded changes are gone for good: git never stored them.
 */
"hard";

/**
 *  A commit given by a ref (`refs/heads/x`, `refs/remotes/origin/x`, `refs/tags/v1`) or by id.
 *  Naming the ref lets git word the merge message after it.
 */
export type Rev = 
/**  A ref by full name. */
{ kind: "ref"; name: string } | { kind: "commit"; id: Oid };

export type Row = {
	kind: RowKind,
	/**  Commit id; [`Oid::ZERO`] for the uncommitted-changes row. */
	id: Oid,
	graph: GraphRow,
	/**  First line of the commit message. */
	summary: string,
	authorName: string,
	authorEmail: string,
	/**  Author time, seconds since the Unix epoch. 0 for the uncommitted-changes row. */
	time: number,
	/**  Labels to show on this row, in display order (HEAD's branch first). */
	refs: RefLabel[],
	/**  Branches splitting off or joining at this row, in lane order. Empty for most rows. */
	relations: Relation[],
};

export type RowKind = "commit" | 
/**  Uncommitted changes in the worktree or index, drawn as a child of HEAD. */
"workingTree" | "stash";

/**  Where a row is in one snapshot. A row index means nothing without its generation. */
export type RowLocation = {
	generation: Generation,
	/**  Index of the row; `None` if no row of this snapshot shows the requested id. */
	row: number | null,
};

/**  A contiguous run of graph rows from one snapshot. */
export type RowsPage = {
	generation: Generation,
	/**  Index of `rows[0]`. Requests past the end are clamped, so this may be less than requested. */
	start: number,
	/**  Total rows in this snapshot. */
	total: number,
	rows: Row[],
};

/**
 *  Identifies one open session (a tab in the UI) for as long as it is open. Never reused within a
 *  process, so a request or event naming a closed session can't reach one opened after it.
 */
export type SessionId = number;

export type Signature = {
	name: string,
	email: string,
	/**  Seconds since the Unix epoch. */
	time: number,
	/**  The author's UTC offset in minutes (e.g. +120 for UTC+2). */
	offsetMinutes: number,
};

/**  What [`Operation::Undo`] would do now. */
export type Undoable = 
/**
 *  The operation `entry` can be undone: `changes` are the refs that go back to `before`, and
 *  `head` is the HEAD that is restored if HEAD moves too.
 */
{ kind: "ready"; entry: OpId; operation: Operation; 
/**  When it started, milliseconds since the Unix epoch. */
startedAtMs: number; changes: RefChange[]; head: string | null } | 
/**  The most recent operation can't be undone, for `reason`. */
{ kind: "blocked"; operation: Operation; reason: string } | 
/**  No operation on this repository was recorded, or all have been undone. */
{ kind: "nothing" };

export type Upstream = {
	/**  Short name of the upstream remote-tracking branch, e.g. `origin/main`. */
	name: string,
	state: UpstreamState,
};

export type UpstreamState = 
/**
 *  The upstream ref exists locally and points to `id`. `ahead` counts commits on the branch the
 *  upstream lacks; `behind` counts commits on the upstream the branch lacks.
 */
{ kind: "tracking"; ahead: number; behind: number; id: Oid } | 
/**
 *  The upstream is configured but its remote-tracking ref doesn't exist (deleted on the remote
 *  and pruned, or never fetched).
 */
{ kind: "gone" };

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

