// Generated by tauri-specta from src-tauri. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Opens the repository containing `path`, replacing any open repository, and starts emitting
	 *  `repoChanged` events for it.
	 */
	openRepo: (path: string) => __TAURI_INVOKE<RepoInfo>("open_repo", { path }),
	/**  Re-reads the open repository. The generation changes only if something visible changed. */
	refresh: () => __TAURI_INVOKE<RepoInfo>("refresh"),
	/**  Rows `start..start + len` of the current snapshot, clamped to the rows that exist. */
	rows: (start: number, len: number) => __TAURI_INVOKE<RowsPage>("rows", { start, len }),
	/**
	 *  Where the row showing `id` (a commit, a stash, or the all-zero id for uncommitted changes) is
	 *  in the current snapshot; `row` is `null` if no row shows it.
	 */
	locate: (id: Oid) => __TAURI_INVOKE<RowLocation>("locate", { id }),
	/**  Full details of one commit; `null` if `id` isn't a commit. */
	commitDetails: (id: Oid) => __TAURI_INVOKE<{
	id: Oid,
	parents: Oid[],
	author: Signature,
	committer: Signature,
	/**  Full commit message. */
	message: string,
	/**  Files changed relative to the first parent (or the empty tree for a root commit). */
	files: FileChange[],
} | null>("commit_details", { id }),
	/**
	 *  Files that differ between `from` and `to`, sorted by path; a `from` of `null` compares against
	 *  nothing. Reads the index and worktree as they are now.
	 */
	changes: (from: 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" } | null, to: DiffSide) => __TAURI_INVOKE<FileChange[]>("changes", { from, to }),
	/**
	 *  How one file differs between `from` (`null`: nothing) and `to`. `path` names the file on the
	 *  `to` side; pass `oldPath` when it was renamed or copied from another path.
	 */
	fileDiff: (from: 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" } | null, to: DiffSide, path: string, oldPath: string | null) => __TAURI_INVOKE<FileDiff>("file_diff", { from, to, path, oldPath }),
};

/** Events */
export const events = {
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
};

/* Types */
/**  The error every command rejects with. The UI shows `message`; `kind` only picks wording. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type ChangeStatus = "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChanged";

export type CommitDetails = {
	id: Oid,
	parents: Oid[],
	author: Signature,
	committer: Signature,
	/**  Full commit message. */
	message: string,
	/**  Files changed relative to the first parent (or the empty tree for a root commit). */
	files: FileChange[],
};

export type DiffLine = {
	kind: LineKind,
	/**  The line without its terminator. */
	text: string,
	/**
	 *  True if this is the last line of its version and that version doesn't end with a newline
	 *  (git's `\ No newline at end of file`).
	 */
	noFinalNewline: boolean,
};

/**  One side of a comparison between two versions of the repository's files. */
export type DiffSide = 
/**  The files of a commit. */
{ kind: "commit"; id: Oid } | 
/**  The staged files: what the next commit would contain. */
{ kind: "index" } | 
/**
 *  The files on disk as git would store them (line endings converted the way git would), plus
 *  untracked files that aren't ignored.
 */
{ kind: "worktree" };

/**
 *  A line segment inside one row.
 * 
 *  A row is split at its node's vertical center. An [`Half::Upper`] segment runs from the row's
 *  top edge at lane `from` to the center at lane `to`; a [`Half::Lower`] segment runs from the
 *  center at lane `from` to the row's bottom edge at lane `to`. A lane passing straight through a
 *  row is one upper and one lower segment with `from == to`. Segments with `from == to ==
 *  GraphRow::column` are the node's own lane arriving or leaving, not a pass-through.
 */
export type Edge = {
	half: Half,
	from: number,
	to: number,
	color: number,
};

export type ErrorKind = 
/**  A command needed an open repository and none is open. */
"noRepository" | "notARepository" | "git" | 
/**  A bug in FerGit. */
"internal";

export type FileChange = {
	/**  Path after the change, `/`-separated. */
	path: string,
	/**  Path before the change, for renames and copies. */
	oldPath: string | null,
	status: ChangeStatus,
	/**
	 *  Added lines; `None` for binary files (a NUL byte in the first 8000 bytes), submodules, and
	 *  files over 8 MiB on either side.
	 */
	additions: number | null,
	/**  Deleted lines; `None` in the same cases as `additions`. */
	deletions: number | null,
};

/**  How one file differs between two sides. */
export type FileDiff = 
/**
 *  Changed lines in hunks with three lines of context, as `git diff` shows them. No hunks means
 *  the contents are identical (a mode-only change, for example).
 */
{ kind: "text"; hunks: Hunk[] } | 
/**  A side is binary: a NUL byte within its first 8000 bytes. */
{ kind: "binary" } | 
/**  A side is larger than 8 MiB. */
{ kind: "tooLarge" } | 
/**
 *  The path is a submodule on at least one side; `old` and `new` are the commits it points to,
 *  `None` where that side has no submodule at the path.
 */
{ kind: "submodule"; old: Oid | null; new: Oid | null };

/**
 *  Identifies one snapshot of a repository. Increases every time the visible state changes, and
 *  keeps increasing across repositories opened in the same process, so the UI can discard any
 *  response or event from an older snapshot, including one of a previously open repository.
 */
export type Generation = number;

/**  Drawable geometry for one row of the graph. */
export type GraphRow = {
	/**  Lane holding this row's node; lane 0 is leftmost. */
	column: number,
	/**  Color index of the node. Unbounded; the UI maps it onto its palette (e.g. modulo its size). */
	color: number,
	/**  Line segments drawn within this row. */
	edges: Edge[],
};

export type Half = "upper" | "lower";

export type Hunk = {
	/**
	 *  First line of the hunk in the old version, 1-based; 0 when the hunk has no old lines (git's
	 *  `@@ -0,0 +1,3 @@`).
	 */
	oldStart: number,
	oldLines: number,
	/**  First line of the hunk in the new version, 1-based; 0 when the hunk has no new lines. */
	newStart: number,
	newLines: number,
	lines: DiffLine[],
};

export type LineKind = "context" | "added" | "removed";

/**  A git object id (SHA-1). Crosses IPC as a 40-character lowercase hex string. */
export type Oid = string;

/**  Declaration order is display order. */
export type RefKind = 
/**  Detached HEAD. */
"head" | "localBranch" | "remoteBranch" | "tag" | "stash";

export type RefLabel = {
	kind: RefKind,
	/**  Short name as the user reads it: `main`, `origin/main`, `v1.0`, `HEAD`, `stash@{0}`. */
	name: string,
	/**  Full ref name: `refs/heads/main`, `refs/remotes/origin/main`, `refs/tags/v1.0`, `HEAD`, `refs/stash`. */
	fullName: string,
	/**  True for the branch HEAD points to, and for the `HEAD` label of a detached HEAD. */
	isHead: boolean,
};

/**
 *  Sent when the open repository changed on disk and a newer snapshot is current. Carries what
 *  `refresh` would return, so the UI handles both the same way.
 */
export type RepoChanged = RepoInfo;

export type RepoInfo = {
	/**  Worktree root, or the git directory for a bare repository. */
	root: string,
	/**  Display name: the last component of `root`. */
	name: string,
	generation: Generation,
	rowCount: number,
	/**  The commit HEAD points to; `None` in a repository without commits. */
	head: Oid | null,
};

export type Row = {
	kind: RowKind,
	/**  Commit id; [`Oid::ZERO`] for the uncommitted-changes row. */
	id: Oid,
	graph: GraphRow,
	/**  First line of the commit message. */
	summary: string,
	authorName: string,
	authorEmail: string,
	/**  Author time, seconds since the Unix epoch. 0 for the uncommitted-changes row. */
	time: number,
	/**  Labels to show on this row, in display order (HEAD's branch first). */
	refs: RefLabel[],
};

export type RowKind = "commit" | 
/**  Uncommitted changes in the worktree or index, drawn as a child of HEAD. */
"workingTree" | "stash";

/**  Where a row is in one snapshot. A row index means nothing without its generation. */
export type RowLocation = {
	generation: Generation,
	/**  Index of the row; `None` if no row of this snapshot shows the requested id. */
	row: number | null,
};

/**  A contiguous run of graph rows from one snapshot. */
export type RowsPage = {
	generation: Generation,
	/**  Index of `rows[0]`. Requests past the end are clamped, so this may be less than requested. */
	start: number,
	/**  Total rows in this snapshot. */
	total: number,
	rows: Row[],
};

export type Signature = {
	name: string,
	email: string,
	/**  Seconds since the Unix epoch. */
	time: number,
	/**  The author's UTC offset in minutes (e.g. +120 for UTC+2). */
	offsetMinutes: number,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

